### ISSUE TITLE
Missing mandatory key on settings-schema.json file

### ISSUE THREAD

**Issue by Odyseus** [NikoKrause/CinnVIIStarkMenu#11]
Hello, @NikoKrause.

The **favorite-button-size** option inside the settings-schema.json file has a missing mandatory key ("units"). The lack of this key will produce an error when trying to place the applet for the first time on a panel, not initializing its settings.

People updating an existing version of the applet will not see the error because the "units" key might already exists on their current settings files.

**Comment by Odyseus** [comment]
Forget about it. I just saw that you already fixed that. :flushed:

**Comment by NikoKrause** [comment]
@Odyseus 
That explains a lot :)
It worked on the machine, when I removed it.
When i tried to check it on another machine, it backfired on me.
I didn't understood why. Needed like half an hour to find out.

I fixed the `this._activeContainer` typo. Thanks for the mail.

**Comment by Odyseus** [comment]
@NikoKrause.

> I didn't understood why. Needed like half an hour to find out.

Well, it took me a while to find out the problem too. In Cinnamon 3.0.7 the errors in glass.log where too generic. But when I tried it on Cinnamon 3.2.x, the errors started with this:

```
info t=2016-11-23T19:22:08.043Z Installing settings for CinnXPStarkMenu@NikoKrause
error t=2016-11-23T19:22:08.044Z Settings key favorite-button-size is missing property unit
```

And that told me exactly where the error was.
