### ISSUE TITLE
CinnVIIStarkMenu 3.2 Beta

### ISSUE THREAD

**Issue by NikoKrause** [NikoKrause/CinnVIIStarkMenu#12]
The menu is now in Beta stage. This means no more new features. Only critical bugs will be fixed (I hope there aren't any).
Some minor improvements as reviewing my bad English have to be done yet. Translations are welcome. If anybody wants to help out with them, I try to translate them on launchpad. Feel free to join.

I changed the name. The VII in CinnVIIStarkMenu equals the Roman 7.

When Beta is finished, the menu will be uploaded on spices.

@BigDaddyonTech @feren
I'd like you to review the settings-schema file, i.e. the settings of the menu. (The readme file is still in progress.) https://github.com/NikoKrause/CinnVIIStarkMenu/blob/master/CinnVIIStarkMenu%40NikoKrause/2.8/settings-schema.json

Feel free to correct bad English and to rephrase words and sentences, if you have the feeling, that the option is not really clear.

After your responses I'm ready to make the needed changes for vertical panel support.

**Comment by Elbullazul** [comment]
@NikoKrause still want french & spanish?

**Comment by NikoKrause** [comment]
@Elbullazul 
Yes. Thanks for the offer. Do you have an account on launchpad?
I'm still experimenting how to handle translations on launchpad and import them into Github.

Also you should wait till BigDaddyonTech and feren are finished with rephrasing the files.
I come back to you, when I think it's time to translate, ok?

**Comment by Elbullazul** [comment]
@NikoKrause no problem. yes, I have a launchpad, but I don't use it very often

**Comment by NikoKrause** [comment]
>  yes, I have a launchpad, but I don't use it very often

That's great. I think translating on launchpad has the advantage, that you get suggestions, if a translation already exists somewhere else. E.g. you don't have to retranslate the strings, which are the same as in the stock menu. You just have to choose from the suggested translations.

**Comment by NikoKrause** [comment]
@Odyseus
Thanks again! The new file removed the errors. And the permission denied error was, because I forgot to set writing access to the new script file o.O

**Comment by dominichayesferen** [comment]
@lestcape Just to let you know, Makulu's patched version of your Configurable Menu works flawlessly in Cinnamon 3.2 from the looks of it...

**Comment by Elbullazul** [comment]
@NikoKrause one bug is annoying: in the previous releases, starkmenu grabbed the .menu styling. It doesn't in Cinnamon 3.2.

**Comment by cinnamoner** [comment]
I'm sure it'll be sorted out.

**Comment by cinnamoner** [comment]
> Just to let you know, Makulu's patched version of your Configurable Menu works flawlessly in Cinnamon 3.2 from the looks of it...

@feren 

1. You mean the one hacked out from the public Lindoz beta iso available on SourceForge, right?
2. No issues at all on 3.2.2?

**Comment by cinnamoner** [comment]
> After your responses I'm ready to make the needed changes for vertical panel support.

@NikoKrause Is there vertical mounting of the startmenu in Windows Vista/7? Hmmm.

**Comment by cinnamoner** [comment]
Damn, I think I'm gonna download 18.1 once more. Had already but erased the iso. Just for StarkMenu. Your applet doubles user experience on Cinnamon. I'm into Plasma :)

**Comment by NikoKrause** [comment]
@Ellbullazul
Do you mean the menu-background?
https://github.com/linuxmint/Cinnamon/commit/0ac6f0d52caecb5028125e0f20c38fa8e403def6

**Comment by Elbullazul** [comment]
@NikoKrause yeah, probably is that piece of code that does the change. But i need to restart cinnamon nonetheless every time I change theme...

**Comment by NikoKrause** [comment]
Can you hell me figure out the issue you have? I think I don't know what you mean exactly.

Which issue are you observing? How does it worked in 3.0 and what changed in 3.2?
Maybe some steps to reproduce. What does the menu do and what are you expecting it to do instead?

When you say it grabbed .menu styling and now it doesn't, I'll expect it to look ugly. But using the default themes Mint-X and Mint-Y it looks good to me. So I think you mean something else, which I'm not aware of.

**Comment by Elbullazul** [comment]
here's a couple screenies illustrating the bug:

- 3.0
![screenshot_2016-12-19_17-38-13](https://cloud.githubusercontent.com/assets/15310985/21331771/419d8238-c612-11e6-8a60-f081b197a103.png)

- 3.2
![virtualbox_linux mint 18 1_19_12_2016_17_39_00](https://cloud.githubusercontent.com/assets/15310985/21331756/349d7bce-c612-11e6-92f4-60260f6dfb98.png)

you see the change in the stark menu background? in 3.0, it takes the 
```css
.menu-background
```
property, but in 3.2 it doesn't, instead taking the 
```css
.menu
```
settings. maybe it's my theme who's not complete, but then the default menu applet takes the theming allright:
![virtualbox_linux mint 18 1_19_12_2016_17_44_07](https://cloud.githubusercontent.com/assets/15310985/21331858/c84364c4-c612-11e6-915d-d9bdcc42c797.png)

**Comment by cinnamoner** [comment]
@Elbullazul May I ask you for the wallpaper in your 1st screenie, please. 1080. Thanks.

**Comment by Elbullazul** [comment]
![desktop nature wallpaper](https://cloud.githubusercontent.com/assets/15310985/21332050/f99f299e-c613-11e6-8039-daaf58bce95c.png)

royale dark wallpaper in xp, best quality i could find...

**Comment by NikoKrause** [comment]
Okay. It should be the commit I mentioned above. But why does CinnXP looks normal in 3.2? I haven't seen petruzzi updating bis Themen o.O

**Comment by Elbullazul** [comment]
no, it's my theme in the [Redmond themes repo](https://github.com/Elbullazul/Redmond-Themes/tree/master/Windows%20XP%20Luna)

**Comment by NikoKrause** [comment]
Ah okay. The fix is something, what will break the menu for versions < 3.2.
I'm still waiting for my English proofreader ;)

**Comment by cinnamoner** [comment]
@Elbullazul Thanks for the wallpaper.
@NikoKrause Could you post what's to be proofread?

**Comment by cinnamoner** [comment]
@raymerjacque Have you been here?

**Comment by NikoKrause** [comment]
@BigDaddyonTech @feren 
Coulld you tell me, when you get the time to review the menus settings? I mean the msgid-Strings in this file here: https://github.com/NikoKrause/CinnVIIStarkMenu/blob/master/CinnVIIStarkMenu%40NikoKrause/po/CinnVIIStarkMenu.pot
And could you also check the README file. 
Please feel free to rephrase the strings, e.g. if you think it sounds strange...

**Comment by cinnamoner** [comment]
@NikoKrause I've felt some a little too verbose. Also, the menu is not a person to be provided with a password. *To uninstall, enter your password.* sounds better. And no *please*. The menu is too polite :)

**Comment by dominichayesferen** [comment]
@NikoKrause I took a once over of it BTW

**Comment by NikoKrause** [comment]
@feren 
This sentence makes no sense to me. o.O

**Comment by NikoKrause** [comment]
@Elbullazul 
Feel free to translate into French&Spanish now.
I already did some work on those translations, i.e. I "translated" the strings, which are the same as in Cinnamon. Could you please review them as well, if I did everything right?

**Comment by dominichayesferen** [comment]
@NikoKrause I looked over the English translations, will make some noob-friendly correction suggestions soon (DONE)

**Comment by NikoKrause** [comment]
Is anybody of you good with Gimp?
I need an icon for the StarkMenu.i
My idea is having an orb like in Win7 (http://www.tech2date.com/wp-content/uploads/2011/07/Change-Windows-7-Start-Orb.jpg)  , but with the New Cinnamon Logo (http://segfault.linuxmint.com/wp-content/uploads/2016/09/CinnamonIcon5-1.png)

So something similar like eine here with the ubuntu Logo http://img05.deviantart.net/623f/i/2010/164/3/5/ubuntu_orb_pack_3_by_leepat0302.jpg

**Comment by ghost** [comment]
@NikoKrause  https://gist.github.com/lestcape

**Edit:** I'm not an artist, but i can create "goods" scalable (svg) icons...

**Comment by NikoKrause** [comment]
@lestcape 
I like the first one. But the ubuntu orb was just an example.
Do you think you can get the marble/orb/shiny effect of the win7 sign into the cinnamon icon?

EDIT:
If not, could you write CinnVIIStarkMenu instead of Cinnamon under cinna-ubuntu?

**Comment by ghost** [comment]
@NikoKrause change a text in inkscape it's easy, but you are sure that you want a text? What it's the icon size? This is important to know the font and the size font to be used. I think for short sizes a text look really bad...

I can try to create a similar marble/orb/shiny effect... but i can not promised anything... Will help a lot if we found the windows icon in svg format.

**Comment by NikoKrause** [comment]
I want this icon for cinnamon-spices website and for launchpad.net

I'm not sure about spices icon size, but on launchpad there are three types I can set
1. icon: 14x14px
2. logo: 64x64px
3. brand: 192x192px

Maybe one icon with text for the larger images and one icon without text for the smaller.

I didn't found the win7 orb as SVG, but something similar: https://upload.wikimedia.org/wikipedia/en/archive/5/56/20080320183041!WinOrb.svg
Maybe it helps.

Edit:
Or another ORB: http://mondspeer.deviantart.com/art/The-Mana-Orb-a-tribute-to-Diablo-I-475815560

**Comment by Odyseus** [comment]
Hello, guys.

Here is a Windows start orb a little more similar to the original. [window-start-orb.svg.zip](https://github.com/NikoKrause/CinnVIIStarkMenu/files/678555/window-start-orb.svg.zip)

**Comment by dominichayesferen** [comment]
@NikoKrause 
![window-start-orb svg](https://cloud.githubusercontent.com/assets/11057934/21564438/806266e8-ce85-11e6-920f-1c0b5089dbbe.png)

**Comment by ghost** [comment]
https://gist.github.com/lestcape/688afd19331a0d19659bec6cfcb98274#file-starkmenu-svg

This is what i can do...

**Comment by ghost** [comment]
With the help of the @Odyseus icon: https://gist.github.com/lestcape/2fb3cfc219230e39b2fb540b1e3c3c3e

Definitely the blue it's the color to do that,

**Comment by ghost** [comment]
The @Odyseus in blue: https://gist.github.com/lestcape/84ae2f387b955e9c3d637b0f1c203ea2

**Comment by ghost** [comment]
And finally this: https://gist.github.com/lestcape/69cf05e8bce7e831597d8eca774d4dab you need to decide... Tell me to delete this icons.

**Comment by ghost** [comment]
Just an advice, do not try to update your system if you use  the cinnamon nightly repo, it's broken again.

**Comment by dominichayesferen** [comment]
@NikoKrause Could you add the ability to completely hide the User Picture in the menu, and also add an option to use your user name on the 'Home' or any quicklauncher?

**Comment by ghost** [comment]
Hey people, sorry, but some of you can explain me this section of the cinnamon code?
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L1836-L1846

```
        menuItem._activeChangeId = menuItem.connect('active-changed', Lang.bind(this, function (menuItem, active) {
            if (active && this._activeMenuItem != menuItem) {
                if (this._activeMenuItem)
                    this._activeMenuItem.setActive(false);
                this._activeMenuItem = menuItem;
                this.emit('active-changed', menuItem);
            } else if (!active && this._activeMenuItem == menuItem) {
                this._activeMenuItem = null;
                this.emit('active-changed', null);
            }
}));
```

In my opinion this mean, that if some element performs an active-changed, then it's will also emit again the same signals that also was currently emitted, and change the booleam parameter to an object parameter... If I'm ok duplicate the signals it's just a good way for clutter or this have some utility?

**Comment by ghost** [comment]
I see what is doing the function... send an event to the parent of the menu parent of the item...

**Comment by NikoKrause** [comment]
@lestcape @Odyseus @feren 
Thanks for your help with the icon. You helped me a lot. I saved them and will look into it.

@feren 
> Could you add the ability to completely hide the User Picture in the menu, 

I onced tried to add an option to hide the user picture. I ran into some problems, I'm not sure anymore which they were. Can you open a new issue/feature request for that. I will probably look into it for 3.4.

> and also add an option to use your user name on the 'Home' or any quicklauncher?

You can use any label you want for the `Home` or any other quicklauncher. So you can also type in your username.

**Comment by NikoKrause** [comment]
I updated the applet for 3.2.
Vertical panels are working now.

@Elbullazul 
You can now fix your XP themes.

**Comment by dominichayesferen** [comment]
@NikoKrause For the username, I was just thinking so that if one distro wanted to have it set to the user name, that'd make that possible

**Comment by Elbullazul** [comment]
@NikoKrause big thanks! We'll work on it ASAP

**Comment by NikoKrause** [comment]
> @NikoKrause For the username, I was just thinking so that if one distro wanted to have it set to the user name, that'd make that possible

I don't know about that. For 3.4 I'll maybe simplify the "Custom Quicklauncher" settings. There is a file chooser, which can be used for "Home", "Pictures", etc. This would make it easier to add custom folders to menu.

I'll keep it in mind, but I can't promise to implement this.

**Comment by NikoKrause** [comment]
End of BETA.

CinnVIIStarkMenu is ready to launch spices.
Unfortunately it's not possible to upload new applets on spices.
Have to wait, till the migration of the applets to GitHub is done and how it will be done.

**Comment by dominichayesferen** [comment]
@NikoKrause Try making a Pull Request to add it to the GH repo in time for the conversion, it's on Clem's GH

**Comment by cinnamoner** [comment]
Is it on Cinnamon Look? Yeah, Cinnamon Look. Feren's Cinn7 is there. Probably the nicest shell for Stark.

**Comment by NikoKrause** [comment]
Is anybody of you using Cinnamon 3.2? If yes, can anybody try the following:
1. Change theme to Mint-Y.
2. Open xed.
3. Drag it to the left or right screen edge.

Does it tile?
