### ISSUE TITLE
Please fix theming issues

### ISSUE THREAD

**Issue by daemonspudguy** [NikoKrause/CinnVIIStarkMenu#16]
The title says what I mean. I need this start menu.

**Comment by NikoKrause** [comment]
Which themes do you mean?
And which issues? Any Screenshots?

**Comment by Elbullazul** [comment]
you can close it, it's fixed now @ the redmond repo, issue [#18](https://github.com/Elbullazul/Redmond-Themes/issues/18)

**Comment by NikoKrause** [comment]
@jacobpoo 
Did you meant the Redmond Themes? If yes and your issue is fixed, please close the issue.

EDIT: If you meant something else, please feel free to give more infos ;)
