### ISSUE TITLE
[Bug] Menu BG not set instantly on new instance

### ISSUE THREAD

**Issue by dominichayesferen** [NikoKrause/CinnVIIStarkMenu#18]
The StarkMenu Menu BG variable for CinnVIIStarkMenu is not set on the menu when moved to the first applet on CinnXP or added/re-added until a Cinnamon Restart later, whereas it should be themed by StarkMenu Menu BG instantly on new instance and should retain it when moved to the first applet on CinnXP and the likes...

OS: Cinnamon 3.2 on feren OS 2017.0 (Based on 18.1)

**Comment by NikoKrause** [comment]
Can you explain it in other words to me? I don't understand what you did, what you see and what you expect to see. E.g. some steps to reproduce and/or Screenshots.

**Comment by dominichayesferen** [comment]
@NikoKrause When moving the applet to the left on a theme like the latest CinnXP, the applet seems to lose it's Menu BG from beforehand which means it has the normal menu bg instead, also, from what I remember, either setting a theme with SM Menu BG or adding the applet afterwards (I can't remember which order) causes it to also not use the theme's own SM Menu BG but rather the Cinnamon Menu BG...

**Comment by dominichayesferen** [comment]
@NikoKrause Yeah, adding it first after setting the theme doesn't theme it until Cinnamon is restarted...

**Comment by NikoKrause** [comment]
@feren 
I can reproduce it. Can you confirm, if it still happens now with the latest version?

**Comment by dominichayesferen** [comment]
@NikoKrause Hang on, building and making a bootable ISO, will try a bit later

**Comment by dominichayesferen** [comment]
Yep, works now thanks
