### ISSUE TITLE
[Tutorial] How to add l10n/translation support to an applet

### ISSUE THREAD

**Issue by NikoKrause** [NikoKrause/CinnVIIStarkMenu#19]
## Prepare applet.js translation function

Make sure the following two lines are imported in your `applet.js` file:
```js
const GLib = imports.gi.GLib;
const Gettext = imports.gettext;
```
Add the following lines to your applet before `function MyApplet(...)`

```js
// l10n/translation support
const UUID = "yourApplet@You"
Gettext.bindtextdomain(UUID, GLib.get_home_dir() + "/.local/share/locale")

function _(str) {
  return Gettext.dgettext(UUID, str);
}

function MyApplet(metadata, orientation, panelHeight, instance_id) {
......
```
And don't forget to change the `const UUID` above to your applets UUID.

## Prepare applet.js translatable strings

Every String you want to be translated, needs to be put in brackets with underscore `_()`, for example
```js
_("This is a text, which needs to be translated")
```

## Create translation template for the first time

- Create a directory called `po` in the directory of your applet, where the `metadata.json` files is saved.
- Open a terminal in the directory where the `metadata.json` file is saved.
- Type in the command `cinnamon-json-makepot --js po/yourApplet.pot`

The command creates a translation template file `yourApplet.pot` in the `po` directory.

## Create a translation for the first time with the application Poedit

Install the programm "Poedit": `sudo apt install poedit`
* Open Poedit and click on `Create new translation`.
* Open the `yourApplet.pot` file. 
* Once the file is loaded, Poedit will ask you to choose a language for the translation.
* At this point, the `.po` file can be saved and the name will automatically reflect the locale code.

* Poedit usage is pretty much straight forward:
    * There is the Source text box that contains the string to be translated (usually in English).
    * There is the Translation box that will contain the translated text.
    * If there is a `.mo` file saved, when you save your `.po` file, the `.mo` file should be deleted. You could also disable MO files creation from Poedit preferences (go to Edit > Preferences > General tab and uncheck the option called `Automatically compile MO file when saving`).

## Update an existing translation template

- Open a terminal in the directory where the `metadata.json` file is saved.
- Type in the command `cinnamon-json-makepot --js po/yourApplet.pot`

The command overwrites yours translation template file `yourApplet.pot` in the `po` directory.

## Updating an existing translation file
* Open the `.po` file with Poedit.
* Go to the menu `Catalog` and choose the `Update from POT file...` menu item.
* Select `yourApplet.pot` file from which your `.po` file was based on.
* Translate the new untranslated strings and save the changes.

## Testing your translations

The translations will be installed automatically, when the applet is installed through `System Settings > Applets > Applet available (online)`.

If you have installed your applet manually and you want to test your translation:
- Open a terminal in the directory where the `metadata.json` file is saved.
- Type in the command `cinnamon-json-makepot -i`to install the existing translations (i.e. the `.po` files)
- Restart Cinnamon: `CTRL+ALT+ESC`

If you want to remove your translation manually:
- Open a terminal in the directory where the `metadata.json` file is saved.
- Type in the command `cinnamon-json-makepot -r`
- Restart Cinnamon `CTRL+ALT+ESC`

Source for this tutorial is the following tutorial https://github.com/Odyseus/CinnamonTools/wiki/Xlet-localizations by @Odyseus.

**Comment by pdcurtis** [comment]
@NikoKrause
This is a very useful Tutorial. I have a couple of questions for clarification. Am I correct that:

 - One does not have to make any changes in settings-schema.json as all the strings are automatically identified by `cinnamon-json-makepot --js po/yourApplet.pot`
- One has to run   `cinnamon-json-makepot --js po/yourApplet.pot` after **every** change to an applet to create a new `yourApplet.pot`
- lang.po files only need to be changed if one changes the strings which have to be translated and that would normally be done by the translator rather than an applet owner.

**Comment by NikoKrause** [comment]
Hey,

- you don't need to change anything in the settings-schema only in the .js filea. In fact if you run the command without `--js` only the strings in the settings-schema file will be catched.
- No. You don't have to update the template after every change. Only when you changed or added some translatable strings. And even then it's not urgent. The user will then see an untranslated string. No big deal.
- Yes. The .po files are only updated against the .pot file. You don't create the .po files every time from scratch, because you will loose already translated strings. You can leave it up to translator to update the .po file. Or you can "Update from POT file..." and save it with the untranslated strings. It's up to you.

**Comment by germanfr** [comment]
I'd like to add to all this that you cannot use simple quotes on strings in js, because `cinnamon-json-makepot` doesn't recognice them as translatable and does not add them to the generated pot. You have to use double quotes like `_("hello")`.
