### ISSUE TITLE
[Bug] When menu is closed sometimes, it still animates closure

### ISSUE THREAD

**Issue by dominichayesferen** [NikoKrause/CinnVIIStarkMenu#20]
When the menu is closed by clicking outside of it and not on the trigger on the panel, regardless of it animations are off, the closing of the menu will still be animated if done exactly that way...

**Comment by NikoKrause** [comment]
Does this happen with the original menu as well?

**Comment by dominichayesferen** [comment]
@NikoKrause Yep

**Comment by NikoKrause** [comment]
This also happens, when the Escape key is pressed.
This seems to be an error on Cinnamons site. I can't figure out, which part of the code closes the menu, when I press Escape or when I press the mouse outside of the menu. But it doesn't seem to be handled in the applets code itself. At least I couldn't find it :(

**Comment by NikoKrause** [comment]
This seems to be fixed upstream, i.e. this issue should be solved in Linux Mint 18.2.
