### ISSUE TITLE
Czech translation for CinnVIIStarkMenu

### ISSUE THREAD

**Issue by Radek71** [NikoKrause/CinnVIIStarkMenu#22]
[CinnVIIStarkMenu@NikoKrause.po.zip](https://github.com/NikoKrause/CinnVIIStarkMenu/files/819177/CinnVIIStarkMenu.NikoKrause.po.zip)

**Comment by NikoKrause** [comment]
Thanks. I'll import it as soon as possible.

**Comment by NikoKrause** [comment]
I uploaded the translation.
