### ISSUE TITLE
[Tutorial] How to contribute to Cinnamon Spices

### ISSUE THREAD

**Issue by NikoKrause** [NikoKrause/CinnVIIStarkMenu#28]
This is a tutorial, which explains how to contribute to [Cinnamon Spices](https://cinnamon-spices.linuxmint.com) (THEMES, APPLETS, DESKLETS, EXTENSIONS).

## General Info

You can find and install Cinnamon Spices on your Cinnamon machine in `System Settings`:
![screenshot-window-2017-03-13-120458](https://cloud.githubusercontent.com/assets/8415124/23851974/ea486d5c-07e5-11e7-889a-d2752622382a.png)

The code of the Cinnamon Spices is stored on [GitHub](https://github.com/). The code of the
* [THEMES](https://cinnamon-spices.linuxmint.com/themes) is stored on https://github.com/linuxmint/cinnamon-spices-themes
* [APPLETS](https://cinnamon-spices.linuxmint.com/applets) is stored on https://github.com/linuxmint/cinnamon-spices-applets
* [DESKLETS](https://cinnamon-spices.linuxmint.com/desklets) is stored on https://github.com/linuxmint/cinnamon-spices-desklets
* [EXTENSIONS](https://cinnamon-spices.linuxmint.com/extensions) is stored on https://github.com/linuxmint/cinnamon-spices-extensions

The Spices Website is checking every 5 minutes for changes on GitHub. If it detects any new changes on one of those GitHub websites mentioned above, it imports them. So if changes are made on GitHub you see them 5 minutes later on the Spices Website.
For the changes to appear on your machine under `System Settings` it takes longer (several hours).

So to contribute to Cinnamon Spices you will need to learn, how to work on GitHub and how to use `git`, a terminal application, which lets you interact with GitHub.

Wikipedia says:
> GitHub is a web-based Git or version control repository and Internet hosting service. It offers all of the distributed version control and source code management functionality of Git as well as adding its own features. It provides access control and several collaboration features such as bug tracking, feature requests, task management, and wikis for every project.

and 

> Git is a version control system for tracking changes in computer files and coordinating work on those files among multiple people. It is primarily used for software development, but it can be used to keep track of changes in any files. As a distributed revision control system it is aimed at speed, data integrity, and support for distributed, non-linear workflows.

### Create GitHub accound and configure `git`
> This step is for beginners on GitHub. You can skip this step, if you already worked with `git`.

If you want to contribute to Cinnamon Spices (upload and maintain new spices, add translations, fix issues, etc.) you'll need to have an account on GitHub. If you don't have one, you need to [create an account](https://github.com/join?source=header-home).

After you created your account, you need to install and set up `git`. The next few instruction steps have to be done only once:
* To install `git` open a terminal and type in the following command:
```bash
sudo apt-get install git
```
* After `git` has been installed, you need to configure `git`. Type in the following two commands in your terminal:
```bash
git config --global user.name YOUR-GITHUB-NAME
git config --global user.email EMAIL@ADDRESS
```
where `YOUR-GITHUB-NAME` is your GitHub name and `EMAIL@ADDRESS` is your email address you used to sign up on GitHub.
* You can check your configuration with the commands `git config user.name` and `git config user.email`. For me it looks like this:
![screenshot-area-2017-03-13-124337](https://cloud.githubusercontent.com/assets/8415124/23853005/eba699e4-07ea-11e7-9969-3786c5b46536.png)
* I like to change the editor, which is used default by `git`. So I like to change it to an editor I'm used to. The following terminal command changes the editor to `xed` (change this to your favorite editor):
```bash
git config --global core.editor "xed"
``` 

Now you are ready to copy the Cinnamon Spices code you want to work on to your machine.
I'm showing this exemplary for the APPLETS.

### Fork Spices code and copy/clone it to your machine

Go to the GitHub website and sign in.
Then go to one of the GitHub websites, where the code of the Spices is stored. In my case I want to work on the APPLETS so I go to to https://github.com/linuxmint/cinnamon-spices-applets.

You don't do the changes directly on this website, but on a copy of this website, called fork.

* Press the **Fork**-Button at the top right corner (see red rectangle in the image below):
![screenshot-area-2017-03-13-130109](https://cloud.githubusercontent.com/assets/8415124/23853555/5f9bc570-07ed-11e7-9653-4b44dbde5336.png)
 * Now you have a fork of the `cinnamon-spices-applets` repository in your GitHub account at https://github.com/YOUR-GITHUB-NAME/cinnamon-spices-applets ; For example my fork is at https://github.com/NikoKrause/cinnamon-spices-applets and it looks like this:
![screenshot-area-2017-03-13-131006](https://cloud.githubusercontent.com/assets/8415124/23853933/3cb375a6-07ef-11e7-93a0-a423cc433af5.png)
The green box says, that it's `forked from linuxmint/cinnamon-spices-applets`

Now you have to copy the code to your machine:
* Create a directory, where the code should be stored. I created a folder `GitHub` in my `Home` folder.
The terminal command for this is:
```bash
mkdir ~/GitHub
```
* Now go in the terminal to this directory
```bash
cd ~/GitHub
```
* Go to your website https://github.com/YOUR-GITHUB-NAME/cinnamon-spices-applets and press the `Clone or download` button (see red box in the image above). Copy the address (blue box in the image above), which usually looks like this `https://github.com/YOUR-GITHUB-NAME/cinnamon-spices-applets.git`
* Now clone the code to your machine by typing in the terminal
```bash
git clone https://github.com/YOUR-GITHUB-NAME/cinnamon-spices-applets.git
```
* It creates a folder `cinnamon-spices-applets` in your `GitHub` folder. Here you make all your changes. Now got to this directory in your terminal:
```bash
cd ~/GitHub/cinnamon-spices-applets
```
* You are now in a `git` directory. You can check the status:
```bash
git status
```
The output looks like this:
```bash
On Branch master
Your branch is on the same level as 'origin/master'.
Nothing to commit, work list unchanged
```
* You need to tell `git`, that you forked the code:
```bash
git remote add upstream https://github.com/linuxmint/cinnamon-spices-applets.git
```

Now you are ready to contribute to Cinnamon Spices.

## How to make changes and upload them to Cinnamon Spices

As an example we want to add a translation file to the applet [Num Lock/Caps Lock indicator with MessageTray notifications](https://cinnamon-spices.linuxmint.com/applets/view/83)
![screenshot-area-2017-03-13-134007](https://cloud.githubusercontent.com/assets/8415124/23854683/c87753fc-07f2-11e7-984b-fc7700654499.png)

Important informations on the Spices Website are:
The AUTHOR is seen in the red box and the UUID in the green box. Here AUTHOR is `entelechy` and UUID is `betterlock`.

To create the changes we do the following:
* We open a terminal and are going to the directory `UUID/files/UUID` of the APPLET, in our case
```
cd ~/GitHub/cinnamon-spices-applets/betterlock/files/betterlock
```
* NEVER do changes on the master branch. You need to create a new branch. But BEFORE creating a new branch ALWAYS make sure you are on the master branch and up to date.
```
git checkout master
git pull upstream master
```
* Now you can create a new branch. In our example we call our branch `betterlock-translation`:
```
git checkout -b betterlock-translation
```
Check with `git status` that you are on the new created branch. The `-b` flag in the command above says, that you want to create a new branch. If you want to switch between existing branches, that is done with `git checkout BRANCH-NAME`. A list of all your branches will be shown with `git branch`.
* Now we add our translation file to the applet in the applets directory `Home > GitHub > cinnamon-spices-applets > betterlock > files > betterlock`.
* Now `git status` says, that files have been changes:
```bash
On Branch betterlock-translation
Unversed files:
   (use "git add <file> ..." to pre-commit the changes to the commit)
	po/ru.po
Nothing to commit, but there are unversioned files (use "git add" to version)
```
The `po/ru.po` line is red.
* If we happy with our change we add the changed file `po/ru.po` to git to make it ready for upload:
```bash
git add po/ru.po
```
Now if we check with `git status`, the `po/ru.po` line is green.
* We need to tell `git` now, what we did, i.e. create a `commit`
```
git commit
```
The text editor opens and we need to write a proper commit message, which should look like this:
```bash
UUID: A short explanation what we did

A more detailed explanation, if needed
@AUTHOR are you okay with this changes?
```
The @AUTHOR is important. It informs the AUTHOR of the applet, that a change to his applet is requested. He needs to approve your change, before it's added to his applet.
In our example it looks like this:
```
betterlock: added russian translation

@entelechy are you okay with this change?
```
Save the changes in the editor and close the editor.
* Now you need to upload your commit:
```bash
git push
```
The first time you get the following output:
```bash
Fatal: The current branch betterlock-translation does not have an upstream branch.
To send the current branch and the remote branch
As an upstream branch, use
    git push --set-upstream origin betterlock-translation
```
So use the command it says there `git push --set-upstream origin betterlock-translation`. You will be asked for YOUR-GITHUB-NAME and your GITHUB password. When everything was done correctly the changes are now on YOUR GitHub website.

Now you need to create a pull request to the GitHub website of linuxmint. Go to your GitHub website or to the one of linuxmint (it doesn't matter, which one), for our example we go to https://github.com/linuxmint/cinnamon-spices-applets
* There appears a new notification:
![screenshot-area-2017-03-13-141632](https://cloud.githubusercontent.com/assets/8415124/23855918/de6b0064-07f7-11e7-8ff5-8a2bdf447617.png)
* Press the `Compare & pull request` button
* Then press the `Create pull request` button (Use a proper title and a proper commit message for the pull request (like in the commit message)):
![screenshot-area-2017-03-13-141914](https://cloud.githubusercontent.com/assets/8415124/23855995/244c946c-07f8-11e7-9b12-af4b877064c9.png)

You are finished. Now you have to wait till your pull request gets approved and merged or declined and closed.

If you want to make further changes, follow the steps of `How to make changes and upload them to Cinnamon Spices` again. And use every time a DIFFERENT branch.

**Comment by JosephMcc** [comment]
An easier way to push your changes is just `git push origin BRANCH-NAME`
That will push a new branch to your own fork of the repo.

**Comment by pdcurtis** [comment]
@NikoKrause Another nice tutorial. I am glad you show the mechanisms to ensure that the author is alerted to the PL and given the chance to comment. 

Is it however better to tidy up the Branch after the Pull Request has been successfully merged and closed rather than keep every update in a separate branch by deleting it on the local copy and on origin? This can be done by:

```
git push origin --delete <branch_name>
git branch -D <branch_name>
```

Note1:  the forced delete is deliberate as it means that one does not need to merge the branch before deleting as it will eventually appear via the Pull Request from origin to upstream and then the pull from upstream to master.
Note 2; For completeness I believe that when you are working on several machines you may need to purge the stale branch  on the other machines by something like `git fetch --all --prune` on each machine

This keeps your local master and upstream master looking more like upstream and it should have all your commits made to the branch in it via the successful PL including changes made during the merge cycle such as squashing which @brownsr indicated could take place.
