### ISSUE TITLE
When I press the 'Super-R' button, it still opens the default menu and not this one

### ISSUE THREAD

**Issue by NikoKrause** [NikoKrause/CinnVIIStarkMenu#29]
@Reaw
You reported this issue on spices website.
Can you give some more information?
Which Linux Mint version do you use? 
Does this happen also, when you restart Cinnamon?
Does it only happen with SuperR or also with SuperL?

I try to reproduce this later on my machine.

**Comment by Elbullazul** [comment]
@NikoKrause need to restart cinnamon for this to fix, happens with any other cinnamon menu, because somehow a keybind is linked until cinnamon restarts

**Comment by Reaw** [comment]
Thanks very much for the answer, I can't test it now, so I'm gonna try it later and I'll tell you :)

Le 2 mai 2017 23:07:54 GMT+02:00, B00merang Project <notifications@github.com> a écrit :
>@NikoKrause need to restart cinnamon for this to fix, happens with any
>other cinnamon menu, because somehow a keybind is linked until cinnamon
>restarts
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NikoKrause/CinnVIIStarkMenu/issues/29#issuecomment-298761658

-- 
Philippe Bentegeac
