### ISSUE TITLE
[Cinnamon 3.4] Applet can't load

### ISSUE THREAD

**Issue by dominichayesferen** [NikoKrause/CinnVIIStarkMenu#32]
Using the latest version of your applet (Git Master), on Cinnamon 3.4 (Replace 'serena' with 'sonya' on /etc/apt/sources.list.d/official-package-repositories.list), the applet simply stays on Red, and doesn't log any errors, but doesn't appear on the panel, it's probably because the lack of a 3.4 folder, but still...

**Comment by dominichayesferen** [comment]
Don't worry, latest Spices Version fixed it

**Comment by NikoKrause** [comment]
The lack of 3.4 folder is OK.
Yeah. The spices repo has the newest Version and it should work with 3.4
I do not longer use this repo. But I don't want to delete it, because of the git history.

**Comment by dominichayesferen** [comment]
*Make A Note on the top in `<h2>` saying this GitHub Repository is dead then on the README.MD*

**Comment by NikoKrause** [comment]
I probably should

**Comment by Elbullazul** [comment]
@NikoKrause how do you make it work on 3.4? my slingshot menu has same issue but I don't know what to do

**Comment by NikoKrause** [comment]
What do the logs say?

**Comment by dominichayesferen** [comment]
@NikoKrause Just, cannot import Applet.js

**Comment by NikoKrause** [comment]
The glass.log and xsession-errors?

**Comment by dominichayesferen** [comment]
@NikoKrause Glass.log, couldn't see anything in xsession-errors, or didn't check it, hang on

**Comment by dominichayesferen** [comment]
Only thing I can find in my messy XSession Errors is this:
```
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55dbd3e3fb70  Text: 0
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55dbd60083d0  Text: /
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55dbd5ff33b0  Text: 0
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
```

**Comment by NikoKrause** [comment]
Nope

**Comment by NikoKrause** [comment]
> What do the logs say?
>> Just, cannot import Applet.js

The glass log `~/.cinnamon/glass.log` says  a lot more than "just cannot import applet.js"!

```
error t=2017-06-12T13:57:30.080Z redeclaration of let image
trace t=2017-06-12T13:57:30.080Z 
<----------------
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155:13
Extension@/usr/share/cinnamon/js/ui/extension.js:116:5
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449:25
init@/usr/share/cinnamon/js/ui/appletManager.js:47:9
start@/usr/share/cinnamon/js/ui/main.js:454:5
@<main>:1:31
---------------->
error t=2017-06-12T13:57:30.080Z [Applet "slingshot@elbullazul"]: Error importing applet.js from slingshot@elbullazul
error t=2017-06-12T13:57:30.081Z Could not load applet slingshot@elbullazul
```

The important line is the first one: `redeclaration of let image`. Since 3.4 you can't declarate `let` with the same name twice within the same scope/function. So search for `let image` in your applet.js and remove `let` in the second `let image`.

**Comment by NikoKrause** [comment]
@Elbullazul See here https://github.com/linuxmint/cinnamon-spices-applets/pull/888
