### ISSUE TITLE
How do I change the menu icon?

### ISSUE THREAD

**Issue by SimonBaars** [NikoKrause/CinnVIIStarkMenu#48]
Currently, the menu has the following icon for me:

![image](https://user-images.githubusercontent.com/8466614/76611255-813c7700-651a-11ea-8d75-739a7d0435fd.png)

I don't see any option in the configurations to change this. I also can't find the `png` of this icon anywhere. How can I change it?

**Comment by NikoKrause** [comment]
Hey, this repository is outdated. Please use the latest version: https://cinnamon-spices.linuxmint.com/applets/view/281

There's an option in the settings of this applet to use a custom icon.
